<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CRGJO43" failures="0" tests="1" name="Default test" time="0.1" errors="0" timestamp="2022-03-26T13:47:46 IST">
  <testcase classname="testBase.BaseTest" name="@BeforeTest beforeTest" time="0.019">
    <failure type="java.lang.Error" message="Unresolved compilation problems: 
	Syntax error, insert &amp;quot;;&amp;quot; to complete FieldDeclaration
	void is an invalid type for the variable validate_value_from_
">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
Syntax error, insert ";" to complete FieldDeclaration
void is an invalid type for the variable validate_value_from_

at keywords.GenericKeyword.<init>(GenericKeyword.java:349)
at keywords.ValidationKeyword.<init>(ValidationKeyword.java:5)
at keywords.ApplicationKeyword.<init>(ApplicationKeyword.java:12)
at testBase.BaseTest.beforeTest(BaseTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:623)
at org.testng.TestRunner.beforeRun(TestRunner.java:613)
at org.testng.TestRunner.run(TestRunner.java:584)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase classname="testBase.BaseTest" name="@AfterTest tearDown" time="-1.648282666262E9">
    <skipped/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="testCases.CAMS_Login_Test" name="doing_Login" time="0.0">
    <skipped/>
  </testcase> <!-- doing_Login -->
</testsuite> <!-- Default test -->
